### ISSUE TITLE
psyplot gui crashes upon launch

### ISSUE THREAD

**Issue by nobodyinperson** [psyplot/psyplot-gui#31]
#### Code Sample, a copy-pastable example if possible

```bash
psyplot
```

#### Problem description

psyplot gui crashes upon launch

#### Expected Output

psyplot gui opens

<details>
<summary>psyplot</summary>

```bash
Attribute Qt::AA_UseSoftwareOpenGL must be set before QCoreApplication is created.
QWidget: Must construct a QApplication before a QWidget
[1]    3285 IOT instruction (core dumped)  psyplot tests/icon_test.nc
```
</details>

#### Output of ``psyplot -aV``

<details>

```yaml
psyplot:
  requirements:
    matplotlib: 3.5.1
    numpy: 1.22.3
    pandas: 1.4.1
    python: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
    xarray: 0.20.1
  version: 1.4.2+16.g9a1f4f8
psyplot_gui:
  requirements:
    pyqt: 5.15.6
    qt: 5.15.2
    qtconsole: 5.2.2
  version: 1.4.0
```
</details>

#### NOTE

I packaged [`psyplot`](https://aur.archlinux.org/packages/python-psyplot-git) and [`psyplot-gui`](https://aur.archlinux.org/packages/python-psyplot-gui-git) into the AUR.

The above result is the same also when just using `pip install psyplot psyplot-gui`.

OS: Manjaro
